name: glamcode
description: A new Flutter project.
publish_to: 'none'
version: 1.0.8

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  youtube_player_iframe: ^3.1.0
  carousel_slider: ^4.2.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  cached_network_image: ^3.2.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  meta: ^1.8.0
  pinput: ^2.2.19
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  flutter_widget_from_html: ^0.9.0+1
  google_maps_flutter: ^2.2.2
  google_maps_place_picker_mb: ^2.0.0-mb.11
  geocoding: ^2.0.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  syncfusion_flutter_calendar: ^20.4.38
  intl: ^0.18.0
  razorpay_flutter: ^1.3.0
  fluttertoast: ^8.1.2
  url_launcher: ^6.1.7
  swipe_image_gallery: ^0.8.0
  gallery_view: ^1.0.0+1
  video_player: ^2.4.10
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_messaging: ^14.2.1
  firebase_performance: ^0.9.0+9
  firebase_crashlytics: ^3.0.9
  flutter_local_notifications: ^13.0.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/