// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6QgYkFmWK_ryjX-XU41rI--0OQbsao4Q',
    appId: '1:277883075630:web:669f79fb78567a72b8b3bf',
    messagingSenderId: '277883075630',
    projectId: 'glamcode-f8440',
    authDomain: 'glamcode-f8440.firebaseapp.com',
    storageBucket: 'glamcode-f8440.appspot.com',
    measurementId: 'G-LV7CJYZD78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdOT4Hrb9rMVz4ENU4WPQfSU4S3cnJjk',
    appId: '1:277883075630:android:c3c8cdc5961d0bdfb8b3bf',
    messagingSenderId: '277883075630',
    projectId: 'glamcode-f8440',
    storageBucket: 'glamcode-f8440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA95wNFibfnfyYBHryAP0nA5qDfj3FQYwg',
    appId: '1:277883075630:ios:677e5e6918623092b8b3bf',
    messagingSenderId: '277883075630',
    projectId: 'glamcode-f8440',
    storageBucket: 'glamcode-f8440.appspot.com',
    iosClientId: '277883075630-ovp3cjkkak2j25unfe4355tjg7pf23ti.apps.googleusercontent.com',
    iosBundleId: 'com.gonzo.glamcode.glamcode',
  );
}
